import type { Metadata } from "next";
import { kiwiMaru } from "../lib/fonts";
import "./globals.css";
// import Script from "next/script";
import Header from "@/components/header/Header";
// import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${kiwiMaru.className} h-full antialiased bg-background`}
    >
      {/* <head>
        <Script id="adobe-fonts" strategy="afterInteractive">
          {`
            (function(d) {
              var config = {
                kitId: 'hsk3cin',
                scriptTimeout: 3000,
                async: true
              },
              h=d.documentElement,
              t=setTimeout(function(){
                h.className=h.className.replace(/\\bwf-loading\\b/g,"")+" wf-inactive";
              },config.scriptTimeout),
              tk=d.createElement("script"),
              f=false,
              s=d.getElementsByTagName("script")[0],
              a;

              h.className+=" wf-loading";
              tk.src='https://use.typekit.net/'+config.kitId+'.js';
              tk.async=true;

              tk.onload=tk.onreadystatechange=function(){
                a=this.readyState;
                if(f || (a && a!="complete" && a!="loaded")) return;
                f=true;
                clearTimeout(t);
                try {
                  Typekit.load(config);
                } catch(e) {}
              };

              s.parentNode.insertBefore(tk,s)
            })(document);
          `}
        </Script>
      </head> */}

      <body className="min-h-full flex flex-col">
        <Header />
        <main>
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}